### PR TITLE
Finish /forums/new parsing & add tournament parsing

### PR DESCRIPTION
**Pull request by jengel3**
Finished the forums front page and parsing tournament list & indiviual tournaments @gilrosenthal

### CODE REVIEW

**Comment by jengel3** [comment]
Added team parsing with this

`/teams` will return a list of teams parsed from oc.tc/teams

`/teams/:team` will return the name, stats, and a _complete_ list of players from the team page. If there is more than one page of players per team, each page will be queried to get a full list of players, making the request slightly slower, but also the only option to get the full list.

This PR might be of interest to you @javipepe

@gilrosenthal

**Comment by andrgorr** [comment]
Thanks a lot @Jake0oo0 , really didn't find time to do it myself :smiley: 

EDIT: But it doesn't seem to work @gilrosenthal https://overcastapi-gil35.c9.io/player/pmheys

**Comment by jengel3** [comment]
Works for me?

**Comment by jengel3** [comment]
And I think I made it /players/ cause that's more proper for JSON APIs

**Comment by gilrosenthal** [comment]
@javipepe sorry let me update the code, i havent pulled on the server since

**Pull request merged**
